source $HOME/.antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle jameskraai/zshAliases
antigen bundle jameskraai/zshHistory
antigen bundle kennethreitz/autoenv

# Syntax highlighting bundle
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme robbyrussell

antigen-apply

export PATH=$HOME/.bin:$PATH
